use crate::config::keybindings::{BindableAction, KeyBindings};

/// Icon identifiers for the asset system
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Icon {
    // === Tools ===
    Brush,
    Eraser,
    Pencil,
    Line,
    Fill,
    RectSelect,
    EllipseSelect,
    Lasso,
    MagicWand,
    MovePixels,
    MoveSelection,
    PerspectiveCrop,
    ColorPicker,
    CloneStamp,
    Zoom,
    Pan,
    Gradient,
    Text,
    ContentAwareBrush,
    Liquify,
    MeshWarp,
    ColorRemover,
    Smudge,
    Shapes,

    // === UI (toolbar, panels, misc) ===
    Undo,
    Redo,
    ZoomIn,
    ZoomOut,
    ResetZoom,
    Grid,
    GridOn,
    GridOff,
    GuidesOn,
    GuidesOff,
    MirrorOff,
    MirrorH,
    MirrorV,
    MirrorQ,
    WrapPreviewOff,
    WrapPreviewOn,
    Settings,
    Layers,
    Visible,
    Hidden,
    New,
    Open,
    Save,
    Close,
    NewLayer,
    Delete,
    Duplicate,
    Flatten,
    MergeDown,
    MergeDownAsMask,
    AddLayerMaskRevealAll,
    AddLayerMaskFromSelection,
    ToggleLayerMask,
    InvertLayerMask,
    ApplyLayerMask,
    DeleteLayerMask,
    Peek,
    SwapColors,
    CopyHex,
    Commit,
    ResetCancel,
    Expand,
    Collapse,
    Info,
    Search,
    ClearSearch,
    MoveUp,
    MoveDown,
    MoveTop,
    MoveBottom,
    ImportLayer,
    Rename,
    LayerFlipH,
    LayerFlipV,
    LayerRotate,
    LayerProperties,
    LayerAdd,
    LayerDelete,
    LayerDuplicate,
    CurrentMarker,
    ApplyPrimary,
    SoloLayer,
    HideAll,
    ShowAll,
    DropDown,

    // === Settings Tabs ===
    SettingsGeneral,
    SettingsInterface,
    SettingsHardware,
    SettingsKeybinds,
    SettingsAI,

    // === Menu: File ===
    MenuFileNew,
    MenuFileOpen,
    MenuFileSave,
    MenuFileSaveAll,
    MenuFileSaveAs,
    MenuFilePrint,
    MenuFileQuit,

    // === Menu: Edit ===
    MenuEditUndo,
    MenuEditRedo,
    MenuEditCut,
    MenuEditCopy,
    MenuEditPaste,
    MenuEditPasteLayer,
    MenuEditSelectAll,
    MenuEditDeselect,
    MenuEditInvertSel,
    MenuEditColorRange,
    MenuEditPreferences,

    // === Menu: Canvas ===
    MenuCanvasResize,
    MenuCanvasCrop,
    MenuCanvasFlipH,
    MenuCanvasFlipV,
    MenuCanvasRotateCw,
    MenuCanvasRotateCcw,
    MenuCanvasRotate180,
    MenuCanvasAlign,
    MenuCanvasFlatten,

    // === Menu: Color ===
    MenuColorAutoLevels,
    MenuColorDesaturate,
    MenuColorInvert,
    MenuColorInvertAlpha,
    MenuColorSepia,
    MenuColorBrightness,
    MenuColorCurves,
    MenuColorExposure,
    MenuColorHighlights,
    MenuColorHsl,
    MenuColorLevels,
    MenuColorTemperature,

    // === Menu: Filter ===
    MenuFilterBlur,
    MenuFilterGaussian,
    MenuFilterBokeh,
    MenuFilterMotionBlur,
    MenuFilterBoxBlur,
    MenuFilterZoomBlur,
    MenuFilterSharpen,
    MenuFilterSharpenItem,
    MenuFilterReduceNoise,
    MenuFilterDistort,
    MenuFilterCrystallize,
    MenuFilterDents,
    MenuFilterPixelate,
    MenuFilterBulge,
    MenuFilterTwist,
    MenuFilterNoise,
    MenuFilterAddNoise,
    MenuFilterMedian,
    MenuFilterStylize,
    MenuFilterGlow,
    MenuFilterVignette,
    MenuFilterHalftone,
    MenuFilterInk,
    MenuFilterOilPainting,
    MenuFilterColorFilter,
    MenuFilterCanvasBorder,
    MenuFilterGlitch,
    MenuFilterPixelDrag,
    MenuFilterRgbDisplace,
    MenuFilterRemoveBg,

    // === Menu: Generate ===
    MenuGenerateGrid,
    MenuGenerateShadow,
    MenuGenerateOutline,
    MenuGenerateContours,

    // === Menu: View ===
    MenuViewZoomIn,
    MenuViewZoomOut,
    MenuViewFitWindow,
    MenuViewThemeLight,
    MenuViewThemeDark,

    // === UI: Context bar ===
    UiBrushDynamics,
}

impl Icon {
    /// Get the emoji fallback for this icon (used when textures aren't available)
    pub fn emoji(&self) -> &'static str {
        match self {
            // Tools
            Icon::Brush => "[B]",
            Icon::Eraser => "[E]",
            Icon::Pencil => "[P]",
            Icon::Line => "[L]",
            Icon::Fill => "[F]",
            Icon::RectSelect => "[R]",
            Icon::EllipseSelect => "[O]",
            Icon::Lasso => "[L]",
            Icon::MagicWand => "[W]",
            Icon::MovePixels => "[M]",
            Icon::MoveSelection => "[S]",
            Icon::PerspectiveCrop => "[P]",
            Icon::ColorPicker => "[C]",
            Icon::CloneStamp => "[S]",
            Icon::Zoom => "[Z]",
            Icon::Pan => "[H]",
            Icon::Gradient => "[G]",
            Icon::Text => "[T]",
            Icon::ContentAwareBrush => "[A]",
            Icon::Liquify => "[Q]",
            Icon::MeshWarp => "[W]",
            Icon::ColorRemover => "[R]",
            Icon::Smudge => "[Sm]",
            Icon::Shapes => "[Sh]",
            // UI
            Icon::Undo => "<-",
            Icon::Redo => "->",
            Icon::ZoomIn => "[+]",
            Icon::ZoomOut => "[-]",
            Icon::ResetZoom => "1:1",
            Icon::Grid => "[#]",
            Icon::GridOn => "[#]",
            Icon::GridOff => "[ ]",
            Icon::GuidesOn => "[+]",
            Icon::GuidesOff => "[-]",
            Icon::MirrorOff => "[|]",
            Icon::MirrorH => "[|]",
            Icon::MirrorV => "[-]",
            Icon::MirrorQ => "[+]",
            Icon::WrapPreviewOff => "[<>]",
            Icon::WrapPreviewOn => "{<>}",
            Icon::Settings => "\u{2699}",
            Icon::Layers => "[=]",
            Icon::Visible => "\u{1F441}",
            Icon::Hidden => "\u{25CB}",
            Icon::New => "[N]",
            Icon::Open => "[O]",
            Icon::Save => "[S]",
            Icon::Close => "\u{00D7}",
            Icon::NewLayer => "[+]",
            Icon::Delete => "[X]",
            Icon::Duplicate => "[D]",
            Icon::Flatten => "[F]",
            Icon::MergeDown => "[v]",
            Icon::MergeDownAsMask => "[vm]",
            Icon::AddLayerMaskRevealAll => "[M+]",
            Icon::AddLayerMaskFromSelection => "[MS]",
            Icon::ToggleLayerMask => "[M]",
            Icon::InvertLayerMask => "[M!]",
            Icon::ApplyLayerMask => "[MA]",
            Icon::DeleteLayerMask => "[MX]",
            Icon::Peek => "\u{1F50D}",
            Icon::SettingsGeneral => "[G]",
            Icon::SettingsInterface => "[I]",
            Icon::SettingsHardware => "[H]",
            Icon::SettingsKeybinds => "[K]",
            Icon::SettingsAI => "[A]",
            Icon::SwapColors => "[<>]",
            Icon::CopyHex => "\u{2398}",
            Icon::Commit => "\u{2714}",
            Icon::ResetCancel => "\u{2718}",
            Icon::Expand => "\u{25B8}",
            Icon::Collapse => "\u{25C2}",
            Icon::DropDown => "\u{25BE}",
            Icon::Info => "\u{2139}",
            Icon::Search => "\u{1F50D}",
            Icon::ClearSearch => "\u{00D7}",
            Icon::MoveUp => "\u{2191}",
            Icon::MoveDown => "\u{2193}",
            Icon::MoveTop => "\u{21E7}",
            Icon::MoveBottom => "\u{21E9}",
            Icon::ImportLayer => "\u{1F4C2}",
            Icon::Rename => "\u{270F}",
            Icon::LayerFlipH => "\u{2194}",
            Icon::LayerFlipV => "\u{2195}",
            Icon::LayerRotate => "\u{1F504}",
            Icon::LayerProperties => "\u{2699}",
            Icon::LayerAdd => "\u{2795}",
            Icon::LayerDelete => "\u{2796}",
            Icon::LayerDuplicate => "\u{1F4CB}",
            Icon::CurrentMarker => "\u{25B6}",
            Icon::ApplyPrimary => "\u{1F3A8}",
            Icon::SoloLayer => "\u{1F4CD}",
            Icon::HideAll => "\u{1F6AB}",
            Icon::ShowAll => "\u{1F441}",
            // Menu: File
            Icon::MenuFileNew => "\u{1F4C4}",
            Icon::MenuFileOpen => "\u{1F4C2}",
            Icon::MenuFileSave => "\u{1F4BE}",
            Icon::MenuFileSaveAll => "\u{1F4BE}",
            Icon::MenuFileSaveAs => "\u{1F4BE}",
            Icon::MenuFilePrint => "\u{1F5A8}",
            Icon::MenuFileQuit => "\u{274C}",
            // Menu: Edit
            Icon::MenuEditUndo => "\u{21A9}",
            Icon::MenuEditRedo => "\u{21AA}",
            Icon::MenuEditCut => "\u{2702}",
            Icon::MenuEditCopy => "\u{1F4CB}",
            Icon::MenuEditPaste => "\u{1F4CC}",
            Icon::MenuEditPasteLayer => "\u{1F4CC}",
            Icon::MenuEditSelectAll => "\u{2B1C}",
            Icon::MenuEditDeselect => "\u{2B1B}",
            Icon::MenuEditInvertSel => "\u{1F504}",
            Icon::MenuEditColorRange => "\u{1F308}",
            Icon::MenuEditPreferences => "\u{2699}",
            // Menu: Canvas
            Icon::MenuCanvasResize => "\u{1F4D0}",
            Icon::MenuCanvasCrop => "\u{2702}",
            Icon::MenuCanvasFlipH => "\u{2194}",
            Icon::MenuCanvasFlipV => "\u{2195}",
            Icon::MenuCanvasRotateCw => "\u{21BB}",
            Icon::MenuCanvasRotateCcw => "\u{21BA}",
            Icon::MenuCanvasRotate180 => "\u{1F504}",
            Icon::MenuCanvasAlign => "\u{2B1A}",
            Icon::MenuCanvasFlatten => "\u{229F}",
            // Menu: Color
            Icon::MenuColorAutoLevels => "\u{1F532}",
            Icon::MenuColorDesaturate => "\u{25D1}",
            Icon::MenuColorInvert => "\u{1F503}",
            Icon::MenuColorInvertAlpha => "\u{1F532}",
            Icon::MenuColorSepia => "\u{1F4DC}",
            Icon::MenuColorBrightness => "\u{2600}",
            Icon::MenuColorCurves => "\u{1F4C8}",
            Icon::MenuColorExposure => "\u{1F4F7}",
            Icon::MenuColorHighlights => "\u{25D0}",
            Icon::MenuColorHsl => "\u{1F3A8}",
            Icon::MenuColorLevels => "\u{1F4CA}",
            Icon::MenuColorTemperature => "\u{1F321}",
            // Menu: Filter
            Icon::MenuFilterBlur => "\u{1F4A7}",
            Icon::MenuFilterGaussian => "\u{1F4A7}",
            Icon::MenuFilterBokeh => "\u{2B55}",
            Icon::MenuFilterMotionBlur => "\u{27A1}",
            Icon::MenuFilterBoxBlur => "\u{25A3}",
            Icon::MenuFilterZoomBlur => "\u{25CE}",
            Icon::MenuFilterSharpen => "\u{1F4CC}",
            Icon::MenuFilterSharpenItem => "\u{1F4CC}",
            Icon::MenuFilterReduceNoise => "\u{1F50A}",
            Icon::MenuFilterDistort => "\u{1F300}",
            Icon::MenuFilterCrystallize => "\u{1F48E}",
            Icon::MenuFilterDents => "\u{1F30A}",
            Icon::MenuFilterPixelate => "\u{1F9E9}",
            Icon::MenuFilterBulge => "\u{1F534}",
            Icon::MenuFilterTwist => "\u{1F300}",
            Icon::MenuFilterNoise => "\u{1F4A5}",
            Icon::MenuFilterAddNoise => "\u{1F4A5}",
            Icon::MenuFilterMedian => "\u{1F4CA}",
            Icon::MenuFilterStylize => "\u{2728}",
            Icon::MenuFilterGlow => "\u{2728}",
            Icon::MenuFilterVignette => "\u{1F311}",
            Icon::MenuFilterHalftone => "\u{25CF}",
            Icon::MenuFilterInk => "\u{1F58B}",
            Icon::MenuFilterOilPainting => "\u{1F3A8}",
            Icon::MenuFilterColorFilter => "\u{1F3AD}",
            Icon::MenuFilterCanvasBorder => "\u{25A3}",
            Icon::MenuFilterGlitch => "\u{26A1}",
            Icon::MenuFilterPixelDrag => "\u{1F4A2}",
            Icon::MenuFilterRgbDisplace => "\u{1F308}",
            Icon::MenuFilterRemoveBg => "\u{1FA84}",
            // Menu: Generate
            Icon::MenuGenerateGrid => "\u{1F4D0}",
            Icon::MenuGenerateShadow => "\u{1F4A4}",
            Icon::MenuGenerateOutline => "\u{1F58A}",
            Icon::MenuGenerateContours => "\u{1F5FA}",
            // Menu: View
            Icon::MenuViewZoomIn => "\u{1F50D}",
            Icon::MenuViewZoomOut => "\u{1F50D}",
            Icon::MenuViewFitWindow => "\u{229E}",
            Icon::MenuViewThemeLight => "\u{2600}",
            Icon::MenuViewThemeDark => "\u{1F319}",
            // UI: Context bar
            Icon::UiBrushDynamics => "\u{1F3B5}",
        }
    }

    /// Get the tooltip description for this icon (base text without keybind)
    pub fn tooltip(&self) -> &'static str {
        match self {
            // Tools — no hardcoded keybind letters
            Icon::Brush => "Brush Tool",
            Icon::Eraser => "Eraser Tool",
            Icon::Pencil => "Pencil Tool",
            Icon::Line => "Line Tool",
            Icon::Fill => "Fill Tool",
            Icon::RectSelect => "Rectangle Select",
            Icon::EllipseSelect => "Ellipse Select",
            Icon::Lasso => "Lasso Select",
            Icon::MagicWand => "Magic Wand",
            Icon::MovePixels => "Move Selected Pixels",
            Icon::MoveSelection => "Move Selection",
            Icon::PerspectiveCrop => "Perspective Crop",
            Icon::ColorPicker => "Color Picker",
            Icon::CloneStamp => "Clone Stamp",
            Icon::Zoom => "Zoom Tool",
            Icon::Pan => "Pan Tool",
            Icon::Gradient => "Gradient Tool",
            Icon::Text => "Text Tool",
            Icon::ContentAwareBrush => "Content-Aware Brush",
            Icon::Liquify => "Liquify Tool",
            Icon::MeshWarp => "Mesh Warp",
            Icon::ColorRemover => "Color Remover",
            Icon::Smudge => "Smudge Tool",
            Icon::Shapes => "Shapes Tool",
            // UI
            Icon::Undo => "Undo",
            Icon::Redo => "Redo",
            Icon::ZoomIn => "Zoom In",
            Icon::ZoomOut => "Zoom Out",
            Icon::ResetZoom => "Fit to Window",
            Icon::Grid => "Toggle Pixel Grid",
            Icon::GridOn => "Pixel Grid On",
            Icon::GridOff => "Pixel Grid Off",
            Icon::GuidesOn => "Guidelines On",
            Icon::GuidesOff => "Guidelines Off",
            Icon::MirrorOff => "Mirror: Off",
            Icon::MirrorH => "Mirror: Horizontal",
            Icon::MirrorV => "Mirror: Vertical",
            Icon::MirrorQ => "Mirror: Quarters",
            Icon::WrapPreviewOff => "Seamless Edge Preview Off",
            Icon::WrapPreviewOn => "Seamless Edge Preview On",
            Icon::Settings => "Settings",
            Icon::Layers => "Layers",
            Icon::Visible => "Visible",
            Icon::Hidden => "Hidden",
            Icon::New => "New File",
            Icon::Open => "Open File",
            Icon::Save => "Save File",
            Icon::Close => "Close",
            Icon::NewLayer => "New Layer",
            Icon::Delete => "Delete",
            Icon::Duplicate => "Duplicate Layer",
            Icon::Flatten => "Flatten All Layers",
            Icon::MergeDown => "Merge Down",
            Icon::MergeDownAsMask => "Merge Down as Mono-Mask",
            Icon::AddLayerMaskRevealAll => "Add Layer Mask (Reveal All)",
            Icon::AddLayerMaskFromSelection => "Add Layer Mask (From Selection)",
            Icon::ToggleLayerMask => "Enable/Disable Layer Mask",
            Icon::InvertLayerMask => "Invert Layer Mask",
            Icon::ApplyLayerMask => "Apply Layer Mask",
            Icon::DeleteLayerMask => "Delete Layer Mask",
            Icon::Peek => "Peek Layer",
            Icon::SettingsGeneral => "General",
            Icon::SettingsInterface => "Interface",
            Icon::SettingsHardware => "Hardware",
            Icon::SettingsKeybinds => "Keybinds",
            Icon::SettingsAI => "AI",
            Icon::SwapColors => "Swap Colors",
            Icon::CopyHex => "Copy Hex",
            Icon::Commit => "Commit",
            Icon::ResetCancel => "Reset",
            Icon::Expand => "Expand",
            Icon::Collapse => "Collapse",
            Icon::DropDown => "Presets",
            Icon::Info => "Info",
            Icon::Search => "Search",
            Icon::ClearSearch => "Clear Search",
            Icon::MoveUp => "Move Up",
            Icon::MoveDown => "Move Down",
            Icon::MoveTop => "Move to Top",
            Icon::MoveBottom => "Move to Bottom",
            Icon::ImportLayer => "Import Layer from File",
            Icon::Rename => "Rename",
            Icon::LayerFlipH => "Flip Horizontal",
            Icon::LayerFlipV => "Flip Vertical",
            Icon::LayerRotate => "Rotate / Scale",
            Icon::LayerProperties => "Layer Properties",
            Icon::LayerAdd => "Add Layer",
            Icon::LayerDelete => "Delete Layer",
            Icon::LayerDuplicate => "Duplicate Layer",
            Icon::CurrentMarker => "Current",
            Icon::ApplyPrimary => "Apply Primary Color",
            Icon::SoloLayer => "Solo Layer",
            Icon::HideAll => "Hide All Layers",
            Icon::ShowAll => "Show All Layers",
            // UI: Context bar
            Icon::UiBrushDynamics => "Brush Dynamics (Flow, Scatter, Color Jitter)",
            // All menu items — tooltip matches the label
            _ => "",
        }
    }

    /// Map a tool icon to its BindableAction (for dynamic tooltip keybind lookup)
    pub fn bindable_action(&self) -> Option<BindableAction> {
        match self {
            Icon::Brush => Some(BindableAction::ToolBrush),
            Icon::Eraser => Some(BindableAction::ToolEraser),
            Icon::Pencil => Some(BindableAction::ToolPencil),
            Icon::Line => Some(BindableAction::ToolLine),
            Icon::Fill => Some(BindableAction::ToolFill),
            Icon::RectSelect => Some(BindableAction::ToolRectSelect),
            Icon::MagicWand => Some(BindableAction::ToolMagicWand),
            Icon::MovePixels => Some(BindableAction::ToolMovePixels),
            Icon::ColorPicker => Some(BindableAction::ToolColorPicker),
            Icon::CloneStamp => Some(BindableAction::ToolCloneStamp),
            Icon::Zoom => Some(BindableAction::ToolZoom),
            Icon::Pan => Some(BindableAction::ToolPan),
            Icon::Gradient => Some(BindableAction::ToolGradient),
            Icon::Text => Some(BindableAction::ToolText),
            Icon::Lasso => Some(BindableAction::ToolLasso),
            Icon::ColorRemover => Some(BindableAction::ToolColorRemover),
            Icon::MeshWarp => Some(BindableAction::ToolMeshWarp),
            Icon::Shapes => Some(BindableAction::ToolShapes),
            Icon::Undo => Some(BindableAction::Undo),
            Icon::Redo => Some(BindableAction::Redo),
            _ => None,
        }
    }

    /// Get tooltip with the current keybinding appended (e.g. "Brush Tool (B)")
    pub fn tooltip_with_keybind(&self, kb: &KeyBindings) -> String {
        let base = self.tooltip();
        if base.is_empty() {
            return String::new();
        }
        if let Some(action) = self.bindable_action()
            && let Some(combo) = kb.get(action)
        {
            return format!("{} ({})", base, combo.display());
        }
        base.to_string()
    }
}

